### ISSUE TITLE
Possible to move window?

### ISSUE THREAD

**Issue by stuaxo** [stephanh42/rpigl#3]
Hi,
   Is it possible to move / resize the window using vc_dispmanx_element_change_attributes.

I've been trying to work it out in my own code and it's driving me nuts !

S

**Comment by stephanh42** [comment]
Hi Stuart,

Unfortunately I don't know much about dispmanx, I cargo-culted the existing
code from the RPI port of Quake

Stephan.



2016-12-20 1:38 GMT+01:00 Stuart Axon <notifications@github.com>:

**Comment by stuaxo** [comment]
I've been doing the same, it's really tricky since there isn't any available.


In the end, I got it working - these two examples were really good -


In this first one they are using their own window structure, which confused me at first:

https://github.com/munezbn/dispmanx-gst-play/blob/master/dispmanx/dispmanx-window.c#L137

This one is probably the clearest I found:

https://github.com/bbond007/raspytube/blob/85ee6a9ea18fb1d0654483c39b65cd0dcf648d7e/gfxlib.c#L653
